dist: xenial
language: node_js
node_js:
      - 6
      - 8
      - 10
  
cache: yarn

# Don't run builds for renovate PRs, only renovate pushes
if: NOT branch =~ /^renovate\\/.+$/ AND type != pull_request


